### ISSUE TITLE
Unstable tarball has moved

### ISSUE THREAD

**Issue by pathawks** [CVC4/homebrew-cvc4#11]
Trying to install the latest version with `brew install cvc4 --devel` is currently broken.

`https://cvc4.cs.stanford.edu/downloads/builds/src/unstable/latest-unstable.tar.gz` does not exist and currently returns a 403 error. The available files all have a date suffix (ie: `https://cvc4.cs.stanford.edu/downloads/builds/src/unstable/cvc4-2018-03-17.tar.gz`). Perhaps a symlink is missing?

**Comment by 4tXJ7f** [comment]
Thanks for the report. This issue has been finally resolved and merged in #13.
