### ISSUE TITLE
Why do you not send a pull request of the formula to homebrew-core?

### ISSUE THREAD

**Issue by ken-matsui** [CVC4/homebrew-cvc4#26]
If it is incorporated in [homebrew-core](https://github.com/Homebrew/homebrew-core), we do not need to build on client side every time by using the bottle, so it is convenient.
In addition to it, the tap will become unnecessary.
I searched for an existing [PR](https://github.com/Homebrew/homebrew-core/pulls?utf8=✓&q=is%3Apr+cvc4), but a formula incorporated in homebrew-core does not exist seem to be.

Do you have any problems with about send a pull request to homebrew-core?

**Comment by 4tXJ7f** [comment]
@matken11235 Sorry for the late reply. The main reason for having our own tap was originally to make sure that everything works as expected. Now the formula is more stable, so it might be a good idea to submit it when we release CVC4 1.7. One issue with submitting a formula, however, is that the [homebrew docs](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#niche-or-self-submitted-stuff) say that:

> We frown on authors submitting their own work unless it is very popular.

And I am not quite sure if CVC4 meets that requirement.

**Comment by ken-matsui** [comment]
Thank you for your reply.

When `homepage` or `url` using GitHub in a formula, condition the repository is **NOT** <30 forks and <30 watchers, <75 stars.
For the above conditions, `homepage` or `url` of CVC4 is not using GitHub, but probably it follows that is very popular.
Submitting `url` as a repository of GitHub to homebrew-core, BrewTestBot will check if it is popular in GitHub. (https://github.com/Homebrew/homebrew-core/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+GitHub+repository+not+notable+enough)
Even without doing above, upon submitting to homebrew, you can get an answer about whether it is popular or not.

You said you submit it when we release CVC4 1.7, but would it be possible for you to submit 1.6 of the current version to homebrew-core?

**Comment by 4tXJ7f** [comment]
This month is rather busy due to paper deadlines but I'll try to get it in ASAP. As a first step, I've submitted [CryptoMiniSat](https://github.com/Homebrew/homebrew-core/pull/35788) (which is also currently in this homebrew tap).

**Comment by ken-matsui** [comment]
Thank you for submitting it despite your busy schedule. There's no need to rush. I am looking forward to that you submit CVC4.
