### ISSUE TITLE
Installation fails on 10.15

### ISSUE THREAD

**Issue by ccadar** [CVC4/homebrew-cvc4#42]
```
==> ./configure.sh --prefix=/usr/local/Cellar/cvc4/1.7 --symfpu --cryptominisat --python3
==> make install
Last 15 lines from ~/Library/Logs/Homebrew/cvc4/04.make:
2020-07-03 17:42:52 +0100

make
install

make: *** No rule to make target `install'.  Stop.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/cvc4/homebrew-cvc4/issues
```

**Comment by ccadar** [comment]
This looks similar to #32

**Comment by 4tXJ7f** [comment]
Sorry about the long delay. I have updated the tap to install the latest release (1.8) and fixed the `toml` issue. It seems to work both locally (Big Sur) and on GitHub actions (Catalina). Please give it a try and let me know if it works for you.

**Comment by ccadar** [comment]
Thanks, @4tXJ7f.  I've tried it on Big Sur and it works fine now, so I'll close this.
