### ISSUE TITLE
Installation fails after make install on 11.1(macOS Big Sur)

### ISSUE THREAD

**Issue by simplySimple-cs16** [CVC4/homebrew-cvc4#45]
==> make install
Last 15 lines from /Users/kadumperme/Library/Logs/Homebrew/cvc4/04.make:
/tmp/cvc4-20210120-28108-oi7glj/CVC4-1.7/src/theory/uf/kinds: error: no theory content found in file!
make[2]: *** [src/theory/rewriter_tables.h] Error 1
make[2]: *** Deleting file `src/theory/rewriter_tables.h'
make[1]: *** [src/theory/CMakeFiles/gen-theory.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Built target gen-tags-debug
[  2%] Built target gen-tags-trace
[  2%] Generating kind.cpp
[  2%] Generating expr.h
[  2%] Generating expr_manager.h
[  2%] Generating expr.cpp
[  2%] Generating metakind.cpp
[  3%] Generating expr_manager.cpp
[  3%] Built target gen-expr
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/cvc4/homebrew-cvc4/issues

**Comment by moajohansson** [comment]
I seem to have a very similar problem using the home-brew installer (macOS Big Sur 11.2.1)...

==> make install
Last 15 lines from /Users/jomoa/Library/Logs/Homebrew/cvc4/04.make:
2021-02-10 15:00:08 +0100

make
install

make: *** No rule to make target `install'.  Stop.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/cvc4/homebrew-cvc4/issues

**Comment by anton-trunov** [comment]
I get the same error message as @moajohansson (I'm on macOS Big Sur 11.1):
```shell
brew install cvc4/cvc4/cvc4
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Installing cvc4 from cvc4/cvc4
==> Downloading https://files.pythonhosted.org/packages/b9/19/5cbd78eac8b1783671c40e34bb0fa83133a06d340a38b55c645076d40094/toml-0.10.0.tar.gz
Already downloaded: /Users/anton/Library/Caches/Homebrew/downloads/8dd2734c2fe98588801dd538809a3da7987291bd858dfbad935cfabd46090cbb--toml-0.10.0.tar.gz
==> Downloading https://github.com/CVC4/CVC4/archive/1.7.tar.gz
Already downloaded: /Users/anton/Library/Caches/Homebrew/downloads/10a6bf047fc544ed9354fb36e46df90aaa06f0fd43354dc1b610e950288c971a--CVC4-1.7.tar.gz
==> contrib/get-antlr-3.4
==> contrib/get-symfpu
==> ./configure.sh --prefix=/usr/local/Cellar/cvc4/1.7 --symfpu --cryptominisat --python3
==> make install
Last 15 lines from /Users/anton/Library/Logs/Homebrew/cvc4/04.make:
2021-02-11 12:04:35 +0300

make
install

make: *** No rule to make target `install'.  Stop.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/cvc4/homebrew-cvc4/issues
```

Here is the contents of the log file (`/Users/anton/Library/Logs/Homebrew/cvc4/04.make`):
```shell
2021-02-11 12:04:35 +0300

make
install

make: *** No rule to make target `install'.  Stop.

HOMEBREW_VERSION: 3.0.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ebc7cc36a0e029d58fac8cebd1b5ff583b3fd95b
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d1696e62cc1740dd955566dc79a12ac2fbd70e6c
Core tap last commit: 5 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.M8kaEq69D1/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_BOOTSNAP: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit westmere
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
Rosetta 2: true

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python@3.9/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/python@3.9/lib/pkgconfig:/usr/local/opt/gmp/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/coreutils/bin:/usr/local/opt/cmake/bin:/usr/local/opt/python@3.9/bin:/usr/local/opt/pcre/bin:/usr/local/opt/swig/bin:/usr/local/opt/automake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/cryptominisat/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by anton-trunov** [comment]
FWIW, I've found a workaround: 
1. I installed the `toml` package: `/usr/local/bin/python3 -m pip install toml` and
2. downloaded and installed JDK 15.0.2 from Oracle's website.

Perhaps the first step is not necessary.

**Comment by 4tXJ7f** [comment]
Thank you for the report and sorry about the slow response time. We are planning to revisit the Homebrew tap in the near future. The `toml` package should only be necessary when installing `--HEAD` and with future updates to the tap, this shouldn't be necessary either.

**Comment by 4tXJ7f** [comment]
Thank you for your patience. I have updated the tap to install the latest release (1.8) and fixed the `toml` issue. It seems to work both locally (Big Sur) and on GitHub actions (Catalina). Please give it a try and let me know if it works for you.

**Comment by anton-trunov** [comment]
@4tXJ7f Thanks it works for me now! (macOS Big Sur)

**Comment by simplySimple-cs16** [comment]
@4tXJ7f Thanks a lot buddy. You are awesome.
