### ISSUE TITLE
Why limited to x86?

### ISSUE THREAD

**Issue by jakevossen5** [CVC4/homebrew-cvc4#46]
I am trying to install this on M1, but I get an error because of [this line](https://github.com/CVC4/homebrew-cvc4/blob/de029b990d5af6b79b1976acc7e205f2143ab519/Formula/cvc4.rb#L23). [This](https://github.com/CVC4/CVC4/pull/6033) PR apparently fixes compiling on arm64, so is there a reason we depend on x86 here?

**Comment by mpreiner** [comment]
There's no reason to limit this to x86_64. I don't have access to an M1 machine, if you remove the line can you build CVC4?

Note: CVC4 can be built on aarch64 Linux.

**Comment by jakevossen5** [comment]
Yes, but only with the `--HEAD` option (which is expected because the PR linked above went in a couple days ago and there probably hasn't been a release yet)

**Comment by 4tXJ7f** [comment]
Thanks for the report and testing this. We will update the Homebrew tap to support M1 processors for `--HEAD`/future releases.

**Comment by 4tXJ7f** [comment]
I've fixed and changed the formula to allow builds on non-x86 systems. Please give it a try and let me know if it works for you.

**Comment by jakevossen5** [comment]
It seems like what you did should work, but I am still the error. Attached is what I ran

<img width="525" alt="Screen Shot 2021-04-22 at 8 43 03 PM" src="https://user-images.githubusercontent.com/16298666/115810616-76097b00-a3ab-11eb-866e-d2cdd2e56dd3.png">
