### ISSUE TITLE
wrong command to install ?

### ISSUE THREAD

**Issue by pascalpoizat** [CVC4/homebrew-cvc4#7]
Hello

I could not install using
```
brew install cvc4/cvc4/cvc4
```

I had to type:
```
brew install cvc4/homebrew-cvc4/cvc4
```

**Comment by pascalpoizat** [comment]
Cannot reproduce. I close the issue.

**Comment by 4tXJ7f** [comment]
Travis does test it with `cvc4/cvc4/cvc4`, so it *should* work. Please let me know if it occurs again and I'll look into it.

**Comment by pascalpoizat** [comment]
Tried again, and it still works fine. I guess I made a typo somewhere, sorry.
