### ISSUE TITLE
No available formula with the name "antlr@3"

### ISSUE THREAD

**Issue by goodlyrottenapple** [CVC4/homebrew-cvc4#8]
Hi, 
The "antlr@3" formula has been removed from brew, thus breaking this formula.

**Comment by 4tXJ7f** [comment]
Thank you for the heads-up, I'll look into it.

**Comment by 4tXJ7f** [comment]
This should be fixed with #9. Please let me know if it works for you.

**Comment by goodlyrottenapple** [comment]
Thanks, that fixed it
